### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Package path ./lib/context is not exported

### ISSUE THREAD

**Issue by maurice-at-someday** [kodai3/storybook-addon-launchdarkly#10]
When updating the dependency of launchdarkly-react-client-sdk in our app to version `3.0.8` I receive the following error:

```
ModuleNotFoundError: Module not found: Error: Package path ./lib/context is not exported from package C:\repos\someday-frontend\node_modules\launchdarkly-react-client-sdk (see exports field in C:\repos\someday-frontend\node_modules\launchdarkly-react-client-sdk\package.json)
    at <anonymous> (c:\repos\someday-frontend\node_modules\webpack\lib\Compilation.js:2016:28)
    at <anonymous> (c:\repos\someday-frontend\node_modules\webpack\lib\NormalModuleFactory.js:805:13)
    at eval (eval at create (C:\repos\someday-frontend\node_modules\tapable\lib\HookCodeFactory.js:28:14), <anonymous>:10:1)
    at <anonymous> (c:\repos\someday-frontend\node_modules\webpack\lib\NormalModuleFactory.js:272:22)
    at eval (eval at create (C:\repos\someday-frontend\node_modules\tapable\lib\HookCodeFactory.js:28:14), <anonymous>:9:1)
    at <anonymous> (c:\repos\someday-frontend\node_modules\webpack\lib\NormalModuleFactory.js:436:22)
    at <anonymous> (c:\repos\someday-frontend\node_modules\webpack\lib\NormalModuleFactory.js:118:11)
    at <anonymous> (c:\repos\someday-frontend\node_modules\webpack\lib\NormalModuleFactory.js:677:25)
    at <anonymous> (c:\repos\someday-frontend\node_modules\webpack\lib\NormalModuleFactory.js:881:8)
    at <anonymous> (c:\repos\someday-frontend\node_modules\webpack\lib\NormalModuleFactory.js:1001:5)
```

The import from `from 'launchdarkly-react-client-sdk/lib/context'` is no longer valid and it appears the `ReactSdkContext` is no longer exported at all.

**Comment by kodai3** [comment]
Thank you for raising. 
They changed the output path from [3.0.7](https://github.com/launchdarkly/react-client-sdk/commit/9854a95a5e0299078300f346b80864f860501a5c). 😩
I think I can fix in this week.

**Comment by maurice-at-someday** [comment]
I suspected it was the Rollup change that caused this.

Thanks

**Comment by imri29** [comment]
Hey @kodai3, still getting this error, updating to 3.0.9. Any updates on fix eta?

**Comment by kodai3** [comment]
@imri29 
Hi, I couldn't fix it quickly back then and been busy since then.
Actually, I have intension to migrate from LaunchDarkly to other SaaS or self-made system, so fixing this is not my priority...
